### ISSUE TITLE
Missing character warnings with contour lua

### ISSUE THREAD

**Issue by leingang** [pgf-tikz/pgfplots#455] opened 2023-02-23 20:50 UTC
I was getting some warnings about missing characters in my log files. I've isolated the warnings to a contour plot. Here is a MWE:

```TeX
\documentclass{standalone}
\usepackage{pgfplots}
\begin{document}
    \begin{tikzpicture}
        \begin{axis}[
            view={0}{90},
        ]
            \addplot3[
                contour lua,
            ]   {x*y};
        \end{axis}
    \end{tikzpicture}
\end{document}
```

The document compiles fine and produces the expected output, but there are nine identical lines in the `.log` file:

```
Missing character: There is no ` (U+0060) in font nullfont!
...
```

I get these warnings when I accidentally something inside a `tikzpicture` environment that's not parsed by `tikz`. E.g. an extra semicolon or square bracket. So I guess something similar is going on here, but on the `pgfplots` level.

**Comment by hmenke** [comment] 2023-02-24 07:54
This one is going to be tough to track down, because the missing character only appears when we're already inside the shipout box.

```latex
\makeatletter
\errorcontextlines=\maxdimen
\tracinglostchars=3
% prevent resetting \tracinglostchars
\let\normaltracinglostchars=\tracinglostchars
\let\tracinglostchars=\count@
\makeatother
\documentclass{article}
\usepackage{pgfplots}
\begin{document}
    \begin{tikzpicture}
        \begin{axis}[
            view={0}{90},
        ]
            \addplot3[
                contour lua,
            ]   {x*y};
        \end{axis}
    \end{tikzpicture}
\end{document}
```

```latex
Missing character: There is no ` (U+0060) in font nullfont!
.
<argument> ...not:N \tex_shipout:D \box_use:N \l_shipout_box 
                                                  \__shipout_drop_firstpage_...

\use_ii:nn #1#2->#2
                   
<argument> ...t@typeset@protect \hook_use:n {shipout/after}}}
                                                  \cs_set_eq:NN \protect \__...

\use_ii:nn #1#2->#2
                   
<to be read again> \__shipout_execute_cont: 
                         \endgroup \set@typeset@protect 
\@outputpage ...width {\@thefoot }\color@endbox }}
                                                  \global \let \if@newlist \...

\@opcol ...te@singlecol@structures@@ \@outputpage 
                                                  \fi \global \@mparbottom \...

<output> ... <-\@M \@specialoutput \else \@makecol \@opcol 
                                                  \@startcolumn \@whilesw \i...

\newpage ...prevdepth \fi \fi \vfil \penalty -\@M 
                                                  
\clearpage ...opskip \hbox {}\fi \fi \fi \newpage 
                                                  \write \m@ne {}\vbox {}\pe...

<to be read again> 
\the 
<to be read again> 
\pgfutil@everybye 
\__hook enddocument ..._hook_toplevel enddocument 
                                                  \__hook_next enddocument 
\__hook_use_once:n ..._hook_use_initialized:n {#1}
                                                  \__hook_use_once_clear:n {#1}

\enddocument ...ment \UseOneTimeHook {enddocument}
                                                  \@kernel@after@enddocument...

\end  ...ook {env/#1/end}}\csname end#1\endcsname 
                                                  \@checkend {#1}\expandafte...

l.20 \end{document}
```

**Comment by muzimuzhi** [comment] 2023-02-24 14:11
Duplicate of #424, and already fixed in https://github.com/pgf-tikz/pgfplots/commit/a31cac6a9ea2cbabf13962b1c2b2766e2b7d0bf0. Unfortunately, the fix is not released too.

**Closed** 2023-02-24 14:11 UTC

**Comment by leingang** [comment] 2023-02-24 19:28
Sorry I missed the earlier bug report. Thank you in arrears for the fix!
