### ISSUE TITLE
"Fill between" makes thick lines thin

### ISSUE THREAD

**Issue by markusReinert** [pgf-tikz/pgfplots#380] opened 2020-12-02 18:18 UTC
It seems that adding a "fill between" command to a plot makes the plot forget about attributes that change the thickness of lines.

Here is a minimal working example:
```
\documentclass{article}

\usepackage{pgfplots}
\pgfplotsset{compat=1.16}
\usepgfplotslibrary{fillbetween}

\begin{document}

\begin{tikzpicture}
	\begin{axis}[ultra thick]
		\addplot [name path=upper] {+1};
		\addplot [name path=lower] {-1};
		\addplot [opacity=0.1] fill between [of=upper and lower];
	\end{axis}
\end{tikzpicture}

\end{document}
```
The lines in this plot are normal size despite the keyword "ultra thick": [Example with "fill between": lines are thin](https://github.com/pgf-tikz/pgfplots/files/5631246/mwe.pdf)

Commenting the line with the "fill between"-command gives the expected result:
[Example when "fill between" is commented: lines are thick](https://github.com/pgf-tikz/pgfplots/files/5631260/mwe.pdf)

I would expect that the lines stay thick when I re-add the "fill between"-command, but they don't.

This seems like a bug to me.

**Comment by Mo-Gul** [comment] 2020-12-02 20:31
I guess this is a duplicate of issue #138, right?

**Comment by markusReinert** [comment] 2020-12-04 13:19
Yes, that's a duplicate. I'm sorry, I only looked in the most recent issues for a duplicate, I did not go back to 2016. Shall we close this issue because it's a duplicate? I'm not sure what the standard proceedure is.

**Comment by ilayn** [comment] 2020-12-04 14:24
Duplicate of #138

**Closed by ilayn** 2020-12-04 14:24 UTC
Labels: fillbetween
