### ISSUE TITLE
Provide an easy way to display x and y error bars as rectangles 

### ISSUE THREAD

**Issue by dbitouze** [pgf-tikz/pgfplots#410] opened 2021-11-22 20:33 UTC
Currently, `pgfplots` displays by default `x` and `y` error bars as two orthogonal lines. It would be nice to be able to instead display these errors as the (say light gray filled) rectangles circumscribing these orthogonal lines. Stefan Pinnow provided [a solution](https://tex.stackexchange.com/a/411049/18401) for this. Is there any chance it will be directly implemented in `pgfplots`?

**Comment by hmenke** [comment] 2021-11-22 20:38
Exact duplicate of #305.

It is extremely rude to post exact duplicates of your own feature requests to push them to the top.

**Closed by hmenke** 2021-11-22 20:38 UTC

**Comment by dbitouze** [comment] 2021-11-22 20:59
> Exact duplicate of #309.
> 
> It is extremely rude to post exact duplicates of your own feature requests to push them to the top.

Absolutely no attempt to push it to the top, I just forgot I already post it: sorry for the noise.
